### ISSUE TITLE
Deprecated unparenthesized on line 90

### ISSUE THREAD

**Issue by solonalbuquerque** [dcblogdev/pagination#11]
This error:
``Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in ...``

Solution:

Line 90
`$this->_page = ($this->_page == 0 ? 1 : $this->_page < 0 ? 1 : $this->_page);`

Replace to
`$this->_page = ($this->_page == 0 ? 1 : $this->_page < 0) ? 1 : $this->_page;`

**Comment by dcblogdev** [comment]
updated, thank you.
